gnuhealth-control : use UTC date and colors for logging actions

diff --git a/tryton/gnuhealth-control b/tryton/gnuhealth-control
--- a/tryton/gnuhealth-control
+++ b/tryton/gnuhealth-control
@@ -40,7 +40,6 @@ Command:
 
 Options:
 
- --nobackup : Don't do a backup previous to the update. 
  --backdir  : destination directory for the backup file
  --dry-run  : Check, download and preview, but don't actually update process
  --database : database name to use with the update or backup command 
@@ -81,33 +80,44 @@ EOF
     exit 0
 }
 
+cli_msg()
+{
+    local UTC="$(date -u +'%Y-%m-%d %H:%M:%S')"
+    
+    case $1 in
+      ERROR ) echo -e "\e[00;31m${UTC} [ERROR] $2\e[00m";;
+      WARNING ) echo -e "\e[0;33m$UTC [WARNING] $2\e[m" ;;
+      INFO ) echo -e "\e[0;34m$UTC [INFO] $2\e[m" ;;
+    esac
+}
+
 get_current_values()
 {
     # Bail out if no GNU Health profile exists
     if [ ! -e $HOME/.gnuhealthrc ]
     then
-        echo "No GNU Health profile found !"
+        cli_msg "ERROR" "No GNU Health profile found !"
         exit 1
     fi
     
     # Stop if it can't find the GNU Health version
     if [ -z "$GNUHEALTH_VERSION" ]
     then
-        echo "Could not find the GNU Health version env. variable"
+        cli_msg "ERROR" "Could not find the GNU Health version env. variable"
         exit 1
     fi
     
     
-    echo "Environment variables"
-    echo "GNUHEALTH_VERSION = ${GNUHEALTH_VERSION}"
-    echo "PYTHONPATH = $PYTHONPATH"
+    cli_msg "INFO" "Environment variables"
+    cli_msg "INFO" "GNUHEALTH_VERSION = ${GNUHEALTH_VERSION}"
+    cli_msg "INFO" "PYTHONPATH = $PYTHONPATH"
     
 }
 
 do_backup()
 {
     local COMMAND=$1
-    local BACKDATE=`date +%d-%m-%y_%H%M%S`
+    local BACKDATE=`date -u +%Y-%m-%d_%H:%M:%S`
     local LOCKFILE="/tmp/.gnuhealth_backup.lock"
     local INFOFILE="/tmp/gnuhealth_backup.log"
     local BACKDIR=""
@@ -116,8 +126,7 @@ do_backup()
     shift # Remove the command and deal only with the options
     
     if [ $# -ne 4 ]; then
-        echo "Backup usage :"
-        echo "gnuhealth-control backup --backdir <directory> --database <dbname>"
+        echo -e "Usage : gnuhealth-control backup --backdir <directory> --database <dbname>"
         exit
     fi
 
@@ -132,35 +141,30 @@ do_backup()
     
     if [ -f $LOCKFILE ]
     then
-            echo "$BACKDATE : Backup in progress or stale lock file found ..." | tee $INFOFILE
+            cli_msg "ERROR" "Backup in progress or stale lock file found ..." | tee $INFOFILE
             exit
     fi
 
     touch $LOCKFILE
-
-    
-    shift
-    
     
     # Backup start
 
-    echo "$BACKDATE +++ START Database Backup" | tee $INFOFILE
+    cli_msg "INFO" "START Database Backup" | tee $INFOFILE
     
-    pg_dump $DB > $BACKDIR/backup\_$DB4\_$BACKDATE || exit -1 
+    pg_dump $DB > $BACKDIR/backup\_$DB4\_$BACKDATE || exit 1 
 
-    echo "$BACKDATE +++ Compressing Database Backup" | tee $INFOFILE
+    cli_msg "INFO" "Compressing Database Backup" | tee $INFOFILE
 
-    gzip $BACKDIR/backup\_$DB\_$BACKDATE || exit -1
+    gzip $BACKDIR/backup\_$DB\_$BACKDATE || exit 1
     
-    echo "$BACKDATE +++  Creating compressed tarball with DB and GNU Health home directory" | tee $INFOFILE
+    cli_msg "INFO" "Creating compressed tarball with DB and GNU Health home directory" | tee $INFOFILE
 
-    tar -cvf $BACKDIR/gnuhealth_backup\_$BACKDATE $HOME || exit -1
+    tar -cvf $BACKDIR/gnuhealth_backup\_$BACKDATE $HOME || exit 1
 
-    echo "$BACKDATE Backup Successful" | tee $INFOFILE
+    cli_msg "INFO" "Backup Successful" | tee $INFOFILE
 
     #Remove lock file
     rm $LOCKFILE
-
 
 }
 
